core/urls.py
from django.conf.urls import include, url

from rest_framework import routers
from views import ProductoViewSet, ProductoFilterList, ClienteViewSet, ClienteFilterList, ProveedorViewSet, ProveedorFilterList, LoteViewSet, LoteFilterList

router = routers.DefaultRouter()
router.register(r'productos', ProductoViewSet)
router.register(r'lotes', LoteViewSet)
router.register(r'clientes', ClienteViewSet)
router.register(r'proveedores', ProveedorViewSet)

urlpatterns = [
  # Rest API
  url(r'^api/core/', include(router.urls)),
  url(r'^api/productos-filter/$', ProductoFilterList.as_view()),
  url(r'^api/lotes-filter/$', LoteFilterList.as_view()),
  url(r'^api/clientes-filter/$', ClienteFilterList.as_view()),
  url(r'^api/proveedores-filter/$', ProveedorFilterList.as_view()),
]

front/urls.py
from django.conf.urls import  include, url

from . import views

urlpatterns = [
  url(r'^$', views.index, name = 'index'),

  url(r'^login/$', views.the_login, name = 'the_login'),
  url(r'^logout/$', views.the_logout, name = 'the_logout'),

  url(r'^venta/$', views.venta, name = 'venta'),
  url(r'^venta/ver/(?P<id>.*)$', views.venta_view, name = 'venta_view'),
  url(r'^ventas/$', views.ventas, name = 'ventas'),
  url(r'^ventas/json/$', views.ventas_json, name = 'ventas_json'),
  url(r'^venta/print/(?P<id>.*)$', views.venta_print, name = 'venta_print'),
  url(r'^venta/guia/print/(?P<id>.*)$', views.venta_guia_print, name = 'venta_guia_print'),
  url(r'^venta/factura/print/(?P<id>.*)$', views.venta_factura_print, name = 'venta_factura_print'),
  url(r'^venta/editar/$', views.venta_editar, name = 'venta_editar'),
  url(r'^venta/borrar/(?P<id>.*)$', views.venta_delete, name = 'venta_delete'),

  url(r'^amortizacion/(?P<id>.*)$', views.amortizacion, name = 'amortizacion'),

  url(r'^deudas/$', views.deudas, name = 'deudas'),

  url(r'^entrada/$', views.entrada, name = 'entrada'),
  url(r'^entrada/ver/(?P<id>.*)$', views.entrada_view, name = 'entrada_view'),
  url(r'^entradas/$', views.entradas, name = 'entradas'),
  url(r'^entradas/json/$', views.entradas_json, name = 'entradas_json'),
  url(r'^entrada/print/(?P<id>.*)$', views.entrada_print, name = 'entrada_print'),


  url(r'^salida/$', views.salida, name = 'salida'),
  url(r'^salida/ver/(?P<id>.*)$', views.salida_view, name = 'salida_view'),
  url(r'^salidas/$', views.salidas, name = 'salidas'),
  url(r'^salidas/json/$', views.salidas_json, name = 'salidas_json'),
  url(r'^salida/print/(?P<id>.*)$', views.salida_print, name = 'salida_print'),

  url(r'^gasto/$', views.gasto, name = 'gasto'),
  url(r'^gasto/ver/(?P<id>.*)$', views.gasto_view, name = 'gasto_view'),
  url(r'^gastos/$', views.gastos, name = 'gastos'),

  url(r'^clientes/$', views.clientes, name = 'clientes'),
  url(r'^proveedores/$', views.proveedores, name = 'proveedores'),

  url(r'^inventario/$', views.inventario, name = 'inventario'),
  url(r'^inventario/json/$', views.inventario_json, name = 'inventario_json'),
  url(r'^inventario/print/(?P<id>.*)$', views.inventario_print, name = 'inventario_print'),

  url(r'^liquidacion/$', views.liquidacion, name = 'liquidacion'),
  url(r'^liquidacion/print/(?P<fecha>.*)/(?P<id>.*)/(?P<user>.*)$', views.liquidacion_print, name = 'liquidacion_print'),

  url(r'^cotizacion/$', views.cotizacion, name = 'cotizacion'),
  url(r'^cotizacion/ver/(?P<id>.*)$', views.cotizacion_view, name = 'cotizacion_view'),
  url(r'^cotizaciones/$', views.cotizaciones, name = 'cotizaciones'),
  url(r'^cotizacion/print/(?P<id>.*)$', views.cotizacion_print, name = 'cotizacion_print'),

  url(r'^producto/agregar$', views.producto, name = 'producto'),
  url(r'^producto/lote/agregar$', views.producto_lote, name = 'producto_lote'),

  url(r'^informes/varios$', views.varios, name = 'varios'),
  url(r'^historial/(?P<id>.*)$', views.historial, name = 'historial'),

]

hampi/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^', include('reportes.urls')),
    url(r'^', include('front.urls')),
    url(r'^', include('core.urls')),
    url(r'^', include('almacen.urls')),
]

almacen/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from decimal import *

class Almacen(models.Model):
  nombre = models.CharField(max_length = 100)

  class Meta:
    verbose_name = ('Almacén')
    verbose_name_plural = ('Almacenes')

  def __unicode__(self):
    return self.nombre

class Stock(models.Model):
  en_almacen = models.ForeignKey(Almacen)
  lote = models.ForeignKey('core.Lote')
  unidades = models.IntegerField()

class Entrada(models.Model):
  fecha = models.DateField()
  numero_factura = models.CharField(max_length = 60)
  fecha_factura = models.DateField()
  numero_guia = models.CharField(max_length = 60)
  fecha_guia = models.DateField()
  almacen = models.ForeignKey(Almacen)
  notas = models.TextField(blank = True)
  proveedor = models.ForeignKey('core.Proveedor', blank = True, null = True)
  quien = models.ForeignKey(User)
  fecha_entrada = models.DateField(null = True, blank = True)
  hora_entrada = models.CharField(max_length = 20, blank = True, null = True)

  def __unicode__(self):
    return 'Entrada %s' % self.pk

class EntradaDetalle(models.Model):
  entrada_padre = models.ForeignKey(Entrada)
  lote = models.ForeignKey('core.Lote')
  precio_unitario = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  cantidad = models.IntegerField()
  total = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))

class Salida(models.Model):
  fecha = models.DateField()
  numero_factura = models.CharField(max_length = 60)
  fecha_factura = models.DateField()
  numero_guia = models.CharField(max_length = 60)
  fecha_guia = models.DateField()
  almacen = models.ForeignKey(Almacen)
  notas = models.TextField(blank = True)
  quien = models.ForeignKey(User)
  venta = models.ForeignKey('ventas.Venta', blank = True, null = True)

  def __unicode__(self):
    return 'Salida %s' % self.pk

class SalidaDetalle(models.Model):
  salida_padre = models.ForeignKey(Salida)
  lote = models.ForeignKey('core.Lote')
  precio_unitario = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  cantidad = models.IntegerField()
  total = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))

core/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from decimal import *

class Producto(models.Model):
  codigo = models.CharField(max_length = 255, blank = True)
  producto = models.CharField(max_length = 255)
  marca = models.CharField(max_length = 255)
  comercial = models.CharField(max_length = 255, blank = True)
  unidad_medida = models.CharField(max_length = 100)
  procedencia = models.CharField(max_length = 255, blank = True)
  precio_unidad = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  activo = models.BooleanField(default = True)

  def __unicode__(self):
    return self.producto

class Lote(models.Model):
  numero = models.CharField(max_length = 255, blank = True)
  vencimiento = models.DateField(blank = True, null = True)
  producto = models.ForeignKey(Producto)
  precio_costo = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  nrs = models.CharField(max_length = 255, blank = True, null = True)
  vrs = models.CharField(max_length = 255, blank = True, null = True)

  def __unicode__(self):
    return '%s - Lote: %s' % (self.producto.producto, self.numero)

class Segmento(models.Model):
  nombre = models.CharField(max_length = 100)

  def __unicode__(self):
    return self.nombre  

class Cliente(models.Model):
  TIPOS = (
    ('D', 'DNI'),
    ('R', 'RUC'),
  )
  segmento = models.ForeignKey(Segmento)
  codcliente = models.CharField(max_length = 255, blank = True)
  razon_social = models.CharField(max_length = 255)
  tipo_documento = models.CharField(max_length = 1, choices = TIPOS, default = 'R')
  numero_documento  = models.CharField(max_length = 60)
  direccion = models.CharField(max_length = 255, blank = True)
  ciudad = models.CharField("Distrito", max_length = 100, blank = True)
  distrito = models.CharField("Provincia", max_length = 100, blank = True)
  departamento = models.CharField("Departamento", max_length = 100, blank = True)
  telefono = models.CharField(max_length = 50, blank = True)

  def __unicode__(self):
    return self.razon_social

class Proveedor(models.Model):
  razon_social = models.CharField(max_length = 255)
  ruc = models.CharField(max_length = 11)
  direccion = models.CharField(max_length = 100, blank = True)
  ciudad = models.CharField(max_length = 100, blank = True)
  distrito = models.CharField(max_length = 100, blank = True)
  telefono = models.CharField(max_length = 50, blank = True)

  class Meta:
    verbose_name = ('Proveedor')
    verbose_name_plural = ('Proveedores')

  def __unicode__(self):
    return self.razon_social

class TipoGasto(models.Model):
  nombre = models.CharField(max_length = 100)

  class Meta:
    verbose_name = ('Tipo de Gasto')
    verbose_name_plural = ('Tipos de Gasto')

  def __unicode__(self):
    return self.nombre

class Gasto(models.Model):
  almacen = models.ForeignKey('almacen.Almacen')
  quien = models.ForeignKey(User)
  fecha = models.DateField()
  monto = models.DecimalField(max_digits = 10, decimal_places = 2, default = Decimal('0.00'))
  razon = models.TextField()
  tipo = models.ForeignKey(TipoGasto, blank = True, null = True, default = None)

front/models.py
from django.db import models

# Create your models here.

ventas/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from decimal import *

class Venta(models.Model):
  TIPOS = (
    ('P', 'Crédito'),
    ('C', 'Contado'),
  )
  almacen = models.ForeignKey('almacen.Almacen')
  #fecha = models.DateField()
  cliente = models.ForeignKey('core.Cliente')
  vendedor = models.ForeignKey(User)
  total_venta = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  tipo_venta = models.CharField(max_length = 1, choices = TIPOS, default = 'C')

  # Factura
  orden_compra = models.CharField(max_length = 100, blank = True)
  numero_factura = models.CharField(max_length = 60)
  fecha_factura = models.DateField()
  condiciones = models.CharField(max_length = 100, blank = True)
  vencimiento = models.DateField(blank = True, null = True)
  zona = models.CharField(max_length = 100, blank = True)
  hora = models.CharField(max_length = 100, blank = True)

  # Guia
  numero_guia = models.CharField(max_length = 60)
  fecha_emision = models.DateField()
  fecha_traslado = models.DateField()
  procedencia = models.CharField(max_length = 255)
  llegada = models.CharField(max_length = 255)
  vehiculo = models.CharField(max_length = 255, blank = True)
  inscripcion = models.CharField(max_length = 255, blank = True)
  licencia = models.CharField(max_length = 100, blank = True)
  costo = models.CharField(max_length = 100, blank = True)
  transportista = models.CharField(max_length = 255, blank = True)
  ruc_transportista = models.CharField(max_length = 11, blank = True)
  bultos = models.CharField(max_length = 100, blank = True)
  despachador = models.CharField(max_length = 100, blank = True)
  jefe_almacen = models.CharField(max_length = 100, blank = True)
  vb = models.CharField(max_length = 100, blank = True)

  def __unicode__(self):
    return "Venta %s" % self.pk

class VentaDetalle(models.Model):
  registro_padre = models.ForeignKey(Venta)
  lote = models.ForeignKey('core.Lote')
  precio_unitario = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  cantidad = models.IntegerField()
  total = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))

class Deuda(models.Model):
  ESTADOS = (
    ('D', 'Deuda'),
    ('C', 'Cancelado'),
  )
  registro_padre = models.OneToOneField(Venta)
  total = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  estado = models.CharField(max_length = 1, choices = ESTADOS, default = 'D')

class Amortizacion(models.Model):
  deuda = models.ForeignKey(Deuda)
  fecha = models.DateField()
  monto = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  saldo = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  recibido_por = models.ForeignKey(User)

class Cotizacion(models.Model):
  fecha = models.DateField()
  referencia = models.CharField(max_length = 255)
  quien = models.ForeignKey(User)
  cliente = models.ForeignKey('core.Cliente')
  plazo = models.IntegerField()
  validez = models.IntegerField()
  glosa = models.TextField(blank = True)
  total_cotizacion = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))

  class Meta:
    verbose_name = ('Cotización')
    verbose_name_plural = ('Cotizaciones')

class CotizacionDetalle(models.Model):
  registro_padre = models.ForeignKey(Cotizacion)
  lote = models.ForeignKey('core.Lote')
  precio_unitario = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  cantidad = models.IntegerField()

ventas/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from models import Venta, VentaDetalle, Cotizacion, CotizacionDetalle

class VentaForm(ModelForm):
  class Meta:
    model = Venta
    fields = '__all__'

DetalleFormSet = inlineformset_factory(Venta, VentaDetalle, fields='__all__')

class CotizacionForm(ModelForm):
  class Meta:
    model = Cotizacion
    fields = '__all__'

CotizacionDetalleFormSet = inlineformset_factory(Cotizacion, CotizacionDetalle, fields='__all__')

ventas/views.py
from django.shortcuts import render

# Create your views here.

front/templates/front/amortizacion.html
{% extends 'front/base.html' %}
{% block content %}{% load static %}
<div class="page-header">
  <h3><i class="fa fa-file icon-new"></i> Registrar Amortización
    <span class="small pull-right">
      <a class="btn btn-danger btn-sm" href="{% url 'venta_view' deuda.registro_padre.id %}"><i class="fa fa-arrow-left"></i> Regresar</a>
    </span>
  </h3>
</div>
<div class="row">
  <div class="col-md-6">
    <form action="{% url 'amortizacion' deuda.id %}" role="form" method="post" id="the-form">
      <div class="form-group">
        <input type="text" class="form-control datepicker" id="fecha" name="fecha" placeholder="Fecha de la amortización" autocomplete="off" required>
      </div>
      <div class="form-group">
        <input type="number" class="form-control" id="monto" name="monto" step="any" min="0" placeholder="Adelanto" autocomplete="off" required>
      </div>
      <div class="actions">
        <p class="text-center">
          <button class="btn btn-success btn-block "><i class="fa fa-floppy-o"></i> Guardar</button>
          {% csrf_token %}
        </p>
      </div>
    </form>    
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Datos de la deuda</h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item"><label>Cliente:</label> {{ deuda.registro_padre.cliente }}</li>
        <li class="list-group-item"><label>Fecha:</label> {{ deuda.registro_padre.fecha }}</li>
        <li class="list-group-item"><label>Monto Total:</label> {{ deuda.registro_padre.total_venta|floatformat:2 }}</li>
        <li class="list-group-item"><label>Saldo:</label> {{ saldo|floatformat:2 }}</li>
      </ul>
  </div>
</div>

{% endblock %}

{% block js %}
<script src="{% static "front/js/main.js" %}"></script>
<script src="{% static "front/js/amortizacion.js" %}"></script>
{% endblock %}

{% block title %}Registrar Amortización{% endblock %}

front/templates/front/clientes.html
{% extends 'front/base.html' %}
{% block content %}{% load static %}
<div class="page-header">
  <h3><i class="fa fa-file icon-new"></i> Relación de Clientes
    <span class="small pull-right">
      <button class="btn btn-default btn-sm reset"><i class="fa fa-filter"></i> Quitar Filtros</button>
      <a class="btn btn-success btn-sm print" href="{% url 'excel_clientes' %}"><i class="fa fa-file-excel-o"></i> Exportar a Excel</a>
    </span>
  </h3>
</div>

<table class="table table-striped table-bordered small" id="table">
  <thead>
    <tr>
      <th>Razón Social</th>
      <th class="filter-select filter-exact" data-placeholder="Segmento">Segmento</th>
      <th class="filter-select filter-exact" data-placeholder="Tipo de Documento">Tipo de Documento</th>
      <th>Número de Documento</th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th class="filter-select filter-exact" data-placeholder="Distrito">Distrito</th>
      <th class="filter-select filter-exact" data-placeholder="Provincia">Provincia</th>
      <th class="filter-select filter-exact" data-placeholder="Departamento">Departamento</th>
    </tr>
  </thead>
  <tbody>
    {% for cliente in clientes %}
    <tr>
      <td>{{ cliente.razon_social }}</td>
      <td>{{ cliente.segmento }}</td>
      <td>{{ cliente.get_tipo_documento_display }}</td>
      <td>{{ cliente.numero_documento }}</td>
      <td>{{ cliente.direccion }}</td>
      <td>{{ cliente.telefono }}</td>
      <td>{{ cliente.ciudad }}</td>
      <td>{{ cliente.distrito }}</td>
      <td>{{ cliente.departamento }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="9" class="text-center">No hay clientes registradps</td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <th colspan="9" class="ts-pager form-horizontal">
        <button type="button" class="btn first"><i class="icon-step-backward glyphicon glyphicon-step-backward"></i></button>
        <button type="button" class="btn prev"><i class="icon-arrow-left glyphicon glyphicon-backward"></i></button>
        <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
        <button type="button" class="btn next"><i class="icon-arrow-right glyphicon glyphicon-forward"></i></button>
        <button type="button" class="btn last"><i class="icon-step-forward glyphicon glyphicon-step-forward"></i></button>
        <select class="pagesize input-mini" title="Select page size">
          <option selected="selected" value="10">10</option>
          <option value="20">20</option>
          <option value="30">30</option>
          <option value="40">40</option>
          <option value="9999">Todos</option>
        </select>
        <select class="pagenum input-mini" title="Número de página"></select>
      </th>
    </tr>
  </tfoot>
</table>
{% endblock %}

{% block title %}Relación de Clientes{% endblock %}

{% block css %}
<link rel="stylesheet" media="screen" href="{% static "front/bower_components/jquery.tablesorter/css/theme.bootstrap.css" %}">
{% endblock %}
{% block js %}
<script src="{% static "front/bower_components/jquery.tablesorter/js/jquery.tablesorter.min.js" %}"></script>
<script src="{% static "front/bower_components/jquery.tablesorter/js/jquery.tablesorter.widgets.min.js" %}"></script>
<script src="{% static "front/bower_components/jquery.tablesorter/js/jquery.tablesorter.widgets-filter-formatter.min.js" %}"></script>
<script src="{% static "front/bower_components/jquery.tablesorter/addons/pager/jquery.tablesorter.pager.min.js" %}"></script>
<script src="{% static "front/js/table-sorter.js" %}"></script>
{% endblock %}

front/templates/front/entrada-ver.html
{% extends 'front/base.html' %}
{% load mathfilters %}
{% block content %}{% load static %}
<div class="page-header">
  <h3><i class="fa fa-file icon-new"></i> Detalles de la Entrada
    <span class="small pull-right">
      <a class="btn btn-success btn-sm" href="{% url 'entradas' %}"><i class="fa fa-table"></i> Ver todas las entradas</a>
      <a class="btn btn-success btn-sm" href="{% url 'entrada' %}"><i class="fa fa-book"></i> Registrar una entrada</a>
      <a class="btn btn-primary btn-sm" href="{% url 'entrada_print' entrada.id %}"><i class="fa fa-print"></i> Imprimir</a>
      <a class="btn btn-info btn-sm" href="{% url 'anexo_print' entrada.id %}"><i class="fa fa-file-word-o"></i> Anexos</a>
    </span>
  </h3>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="page-header mini">
      <h5>Información</h5>
    </div>
    <div class="form-group">
      <label>Entrada Nro:</label>
      {{ entrada.pk }}
    </div>
    <div class="form-group">
      <label>Almacén:</label>
      {{ entrada.almacen }}
    </div>
    <div class="form-group">
      <label>Fecha:</label>
      {{ entrada.fecha }}
    </div>
    {% if entrada.documento != 'G' %}
    <div class="form-group">
      <label>Proveedor:</label>
      {{ entrada.proveedor }} ({{ entrada.proveedor.ruc }})
    </div>
    {% endif %}
    <div class="form-group">
      <label>Número de factura:</label>
      {{ entrada.numero_factura }}
    </div>
    <div class="form-group">
      <label>Fecha de factura:</label>
      {{ entrada.fecha_factura }}
    </div>
    <div class="form-group">
      <label>Número de guía:</label>
      {{ entrada.numero_guia }}
    </div>
    <div class="form-group">
      <label>Fecha de guía:</label>
      {{ entrada.fecha_guia }}
    </div>
    <div class="form-group">
      <label>Fecha de Entrada:</label>
      {{ entrada.fecha_entrada }}
    </div>
    <div class="form-group">
      <label>Hora de Entrada:</label>
      {{ entrada.hora_entrada }}
    </div>
    <div class="form-group">
      <label>Quien:</label>
      {{ entrada.quien }}
    </div>
    <div class="form-group">
      <label>Notas:</label>
      {{ entrada.notas }}
    </div>
  </div>
  <div class="col-md-8 line-left">
    <div class="page-header mini">
      <h5>Detalles</h5>
    </div>
    <table class="table table-striped able-condensed table-bordered small">
      <thead>
        <tr>
          <th>Código</th>
          <th>Producto</th>
          <th>Lote Nro</th>
          <th>Vencimiento</th>
          <th>Cantidad</th>
          <th>Costo</th>
          <th>Unitario</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody class="detalles">
        {% for detalle in entrada.entradadetalle_set.all %}
        <tr>
          <td>{{ detalle.lote.producto.codigo }}</td>
          <td>{{ detalle.lote.producto }}</td>
          <td>{{ detalle.lote.numero }}</td>
          <td>{{ detalle.lote.vencimiento }}</td>
          <td>{{ detalle.cantidad }}</td>
          <td>{{ detalle.lote.precio_costo|floatformat:6 }}</td>
          <td>{{ detalle.precio_unitario|floatformat:6 }}</td>
          <td>{{ detalle.cantidad|mul:detalle.lote.precio_costo|floatformat:6 }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>  
{% endblock %}

{% block js%}
<script src="{% static "front/js/main.js" %}"></script>
{% endblock %}

{% block title %}Detalles de la entrada{% endblock %}

front/templates/front/historial.html
{% extends 'front/base.html' %}
{% block content %}{% load static %}
<div class="page-header">
  <h3><i class="fa fa-history icon-new"></i> Historial de Producto
  </h3>
</div>

<div class="well">
  <p class="text-center"><i class="fa fa-file text-warning" ></i> {{ producto.producto }}</p>
</div>

<table class="table table-bordered table-striped table-hover">
  <caption>Detalles de Compra</caption>
  <thead>
    <tr>
      <th>Entrada</th>
      <th>Lote</th>
      <th>Proveedor</th>
      <th>Precio Compra</th>
      <th>Fecha</th>
      <th>Ver detalles</th>
    </tr>
  </thead>
  <tbody>
    {% for producto in productos %}
      {% for lote in producto.lote_set.all %}
        {% for entrada in lote.entradadetalle_set.all %}
          <tr>
            <td>{{ entrada.pk }}</td>
            <td>{{ lote.numero }}</td>
            <td>{{ entrada.entrada_padre.proveedor.razon_social }}</td>
            <td>{{ entrada.lote.precio_costo|floatformat:"6" }}</td>
            <td>{{ entrada.entrada_padre.fecha_factura|date:"d b Y" }}</td>
            <td><a href="{% url 'entrada_view' entrada.entrada_padre.pk %}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i></a></td>
          </tr>
        {% endfor %}
      {% endfor %}
    {% endfor %}
  </tbody>
</table>

<table class="table table-bordered table-striped table-hover">
  <caption>Detalles de Venta</caption>
  <thead>
    <tr>
      <th>Venta</th>
      <th>Lote</th>
      <th>Cliente</th>
      <th>Precio Venta</th>
      <th>Fecha</th>
      <th>Documento</th>
      <th>Ver detalles</th>
    </tr>
  </thead>
  <tbody>
    {% for producto in productos %}
      {% for lote in producto.lote_set.all %}
        {% for venta in lote.ventadetalle_set.all %}
          <tr>
            <td>{{ venta.pk }}</td>
            <td>{{ lote.numero }}</td>
            <td>{{ venta.registro_padre.cliente.razon_social }}</td>
            <td>{{ venta.precio_unitario|floatformat:"3" }}</td>
            <td>{{ venta.registro_padre.fecha_factura|date:"d b Y" }}</td>
            <td>{{ venta.registro_padre.numero_factura }}</td>
            <td><a href="{% url 'venta_view' venta.registro_padre.pk %}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i></a></td>
          </tr>      
        {% endfor %}
      {% endfor %}
    {% endfor %}
  </tbody>
</table>
 
{% endblock content %}