core/urls.py
from django.conf.urls import include, url

from rest_framework import routers
from views import ProductoViewSet, ProductoFilterList, ClienteViewSet, ClienteFilterList, ProveedorViewSet, ProveedorFilterList, LoteViewSet, LoteFilterList

router = routers.DefaultRouter()
router.register(r'productos', ProductoViewSet)
router.register(r'lotes', LoteViewSet)
router.register(r'clientes', ClienteViewSet)
router.register(r'proveedores', ProveedorViewSet)

urlpatterns = [
  # Rest API
  url(r'^api/core/', include(router.urls)),
  url(r'^api/productos-filter/$', ProductoFilterList.as_view()),
  url(r'^api/lotes-filter/$', LoteFilterList.as_view()),
  url(r'^api/clientes-filter/$', ClienteFilterList.as_view()),
  url(r'^api/proveedores-filter/$', ProveedorFilterList.as_view()),
]

front/urls.py
from django.conf.urls import  include, url

from . import views

urlpatterns = [
  url(r'^$', views.index, name = 'index'),

  url(r'^login/$', views.the_login, name = 'the_login'),
  url(r'^logout/$', views.the_logout, name = 'the_logout'),

  url(r'^venta/$', views.venta, name = 'venta'),
  url(r'^venta/ver/(?P<id>.*)$', views.venta_view, name = 'venta_view'),
  url(r'^ventas/$', views.ventas, name = 'ventas'),
  url(r'^ventas/json/$', views.ventas_json, name = 'ventas_json'),
  url(r'^venta/print/(?P<id>.*)$', views.venta_print, name = 'venta_print'),
  url(r'^venta/guia/print/(?P<id>.*)$', views.venta_guia_print, name = 'venta_guia_print'),
  url(r'^venta/factura/print/(?P<id>.*)$', views.venta_factura_print, name = 'venta_factura_print'),
  url(r'^venta/editar/$', views.venta_editar, name = 'venta_editar'),
  url(r'^venta/borrar/(?P<id>.*)$', views.venta_delete, name = 'venta_delete'),

  url(r'^amortizacion/(?P<id>.*)$', views.amortizacion, name = 'amortizacion'),

  url(r'^deudas/$', views.deudas, name = 'deudas'),

  url(r'^entrada/$', views.entrada, name = 'entrada'),
  url(r'^entrada/ver/(?P<id>.*)$', views.entrada_view, name = 'entrada_view'),
  url(r'^entradas/$', views.entradas, name = 'entradas'),
  url(r'^entradas/json/$', views.entradas_json, name = 'entradas_json'),
  url(r'^entrada/print/(?P<id>.*)$', views.entrada_print, name = 'entrada_print'),


  url(r'^salida/$', views.salida, name = 'salida'),
  url(r'^salida/ver/(?P<id>.*)$', views.salida_view, name = 'salida_view'),
  url(r'^salidas/$', views.salidas, name = 'salidas'),
  url(r'^salidas/json/$', views.salidas_json, name = 'salidas_json'),
  url(r'^salida/print/(?P<id>.*)$', views.salida_print, name = 'salida_print'),

  url(r'^gasto/$', views.gasto, name = 'gasto'),
  url(r'^gasto/ver/(?P<id>.*)$', views.gasto_view, name = 'gasto_view'),
  url(r'^gastos/$', views.gastos, name = 'gastos'),

  url(r'^clientes/$', views.clientes, name = 'clientes'),
  url(r'^proveedores/$', views.proveedores, name = 'proveedores'),

  url(r'^inventario/$', views.inventario, name = 'inventario'),
  url(r'^inventario/json/$', views.inventario_json, name = 'inventario_json'),
  url(r'^inventario/print/(?P<id>.*)$', views.inventario_print, name = 'inventario_print'),

  url(r'^liquidacion/$', views.liquidacion, name = 'liquidacion'),
  url(r'^liquidacion/print/(?P<fecha>.*)/(?P<id>.*)/(?P<user>.*)$', views.liquidacion_print, name = 'liquidacion_print'),

  url(r'^cotizacion/$', views.cotizacion, name = 'cotizacion'),
  url(r'^cotizacion/ver/(?P<id>.*)$', views.cotizacion_view, name = 'cotizacion_view'),
  url(r'^cotizaciones/$', views.cotizaciones, name = 'cotizaciones'),
  url(r'^cotizacion/print/(?P<id>.*)$', views.cotizacion_print, name = 'cotizacion_print'),

  url(r'^producto/agregar$', views.producto, name = 'producto'),
  url(r'^producto/lote/agregar$', views.producto_lote, name = 'producto_lote'),

  url(r'^informes/varios$', views.varios, name = 'varios'),
  url(r'^historial/(?P<id>.*)$', views.historial, name = 'historial'),

]

hampi/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^', include('reportes.urls')),
    url(r'^', include('front.urls')),
    url(r'^', include('core.urls')),
    url(r'^', include('almacen.urls')),
]

almacen/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from decimal import *

class Almacen(models.Model):
  nombre = models.CharField(max_length = 100)

  class Meta:
    verbose_name = ('Almacén')
    verbose_name_plural = ('Almacenes')

  def __unicode__(self):
    return self.nombre

class Stock(models.Model):
  en_almacen = models.ForeignKey(Almacen)
  lote = models.ForeignKey('core.Lote')
  unidades = models.IntegerField()

class Entrada(models.Model):
  fecha = models.DateField()
  numero_factura = models.CharField(max_length = 60)
  fecha_factura = models.DateField()
  numero_guia = models.CharField(max_length = 60)
  fecha_guia = models.DateField()
  almacen = models.ForeignKey(Almacen)
  notas = models.TextField(blank = True)
  proveedor = models.ForeignKey('core.Proveedor', blank = True, null = True)
  quien = models.ForeignKey(User)
  fecha_entrada = models.DateField(null = True, blank = True)
  hora_entrada = models.CharField(max_length = 20, blank = True, null = True)

  def __unicode__(self):
    return 'Entrada %s' % self.pk

class EntradaDetalle(models.Model):
  entrada_padre = models.ForeignKey(Entrada)
  lote = models.ForeignKey('core.Lote')
  precio_unitario = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  cantidad = models.IntegerField()
  total = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))

class Salida(models.Model):
  fecha = models.DateField()
  numero_factura = models.CharField(max_length = 60)
  fecha_factura = models.DateField()
  numero_guia = models.CharField(max_length = 60)
  fecha_guia = models.DateField()
  almacen = models.ForeignKey(Almacen)
  notas = models.TextField(blank = True)
  quien = models.ForeignKey(User)
  venta = models.ForeignKey('ventas.Venta', blank = True, null = True)

  def __unicode__(self):
    return 'Salida %s' % self.pk

class SalidaDetalle(models.Model):
  salida_padre = models.ForeignKey(Salida)
  lote = models.ForeignKey('core.Lote')
  precio_unitario = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  cantidad = models.IntegerField()
  total = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))

front/models.py
from django.db import models

# Create your models here.

ventas/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from decimal import *

class Venta(models.Model):
  TIPOS = (
    ('P', 'Crédito'),
    ('C', 'Contado'),
  )
  almacen = models.ForeignKey('almacen.Almacen')
  #fecha = models.DateField()
  cliente = models.ForeignKey('core.Cliente')
  vendedor = models.ForeignKey(User)
  total_venta = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  tipo_venta = models.CharField(max_length = 1, choices = TIPOS, default = 'C')

  # Factura
  orden_compra = models.CharField(max_length = 100, blank = True)
  numero_factura = models.CharField(max_length = 60)
  fecha_factura = models.DateField()
  condiciones = models.CharField(max_length = 100, blank = True)
  vencimiento = models.DateField(blank = True, null = True)
  zona = models.CharField(max_length = 100, blank = True)
  hora = models.CharField(max_length = 100, blank = True)

  # Guia
  numero_guia = models.CharField(max_length = 60)
  fecha_emision = models.DateField()
  fecha_traslado = models.DateField()
  procedencia = models.CharField(max_length = 255)
  llegada = models.CharField(max_length = 255)
  vehiculo = models.CharField(max_length = 255, blank = True)
  inscripcion = models.CharField(max_length = 255, blank = True)
  licencia = models.CharField(max_length = 100, blank = True)
  costo = models.CharField(max_length = 100, blank = True)
  transportista = models.CharField(max_length = 255, blank = True)
  ruc_transportista = models.CharField(max_length = 11, blank = True)
  bultos = models.CharField(max_length = 100, blank = True)
  despachador = models.CharField(max_length = 100, blank = True)
  jefe_almacen = models.CharField(max_length = 100, blank = True)
  vb = models.CharField(max_length = 100, blank = True)

  def __unicode__(self):
    return "Venta %s" % self.pk

class VentaDetalle(models.Model):
  registro_padre = models.ForeignKey(Venta)
  lote = models.ForeignKey('core.Lote')
  precio_unitario = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  cantidad = models.IntegerField()
  total = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))

class Deuda(models.Model):
  ESTADOS = (
    ('D', 'Deuda'),
    ('C', 'Cancelado'),
  )
  registro_padre = models.OneToOneField(Venta)
  total = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  estado = models.CharField(max_length = 1, choices = ESTADOS, default = 'D')

class Amortizacion(models.Model):
  deuda = models.ForeignKey(Deuda)
  fecha = models.DateField()
  monto = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  saldo = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  recibido_por = models.ForeignKey(User)

class Cotizacion(models.Model):
  fecha = models.DateField()
  referencia = models.CharField(max_length = 255)
  quien = models.ForeignKey(User)
  cliente = models.ForeignKey('core.Cliente')
  plazo = models.IntegerField()
  validez = models.IntegerField()
  glosa = models.TextField(blank = True)
  total_cotizacion = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))

  class Meta:
    verbose_name = ('Cotización')
    verbose_name_plural = ('Cotizaciones')

class CotizacionDetalle(models.Model):
  registro_padre = models.ForeignKey(Cotizacion)
  lote = models.ForeignKey('core.Lote')
  precio_unitario = models.DecimalField(max_digits = 19, decimal_places = 6, default = Decimal('0.000000'))
  cantidad = models.IntegerField()

ventas/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from models import Venta, VentaDetalle, Cotizacion, CotizacionDetalle

class VentaForm(ModelForm):
  class Meta:
    model = Venta
    fields = '__all__'

DetalleFormSet = inlineformset_factory(Venta, VentaDetalle, fields='__all__')

class CotizacionForm(ModelForm):
  class Meta:
    model = Cotizacion
    fields = '__all__'

CotizacionDetalleFormSet = inlineformset_factory(Cotizacion, CotizacionDetalle, fields='__all__')

ventas/views.py
from django.shortcuts import render

# Create your views here.

front/templates/front/pdf/cotizacion.html
{% load mathfilters %}
<!doctype html>
<html>
  <head>
    {% include 'front/pdf/styles.html' %}
  </head>
  <body>
    {% include 'front/pdf/meta.html' %}
    <div class="main-title">
      <h2 class="line-up-down line-grey simple-shadow padding">COTIZACIÓN</h2>
    </div>

    <div class="info">
      <p>
        Cusco, {{ cotizacion.fecha }} 
      </p>
      <p>
        Señores:<br>
        {{ cotizacion.cliente }} ({{ cotizacion.cliente.numero_documento }})
      </p>
      <p>Att: Unidad de Logística</p>
      <p class="line-down text-right big">
        <strong>Referencia:</strong> "{{ cotizacion.referencia }}"
      </p>
    </div>

    <div class="details">
      <table class="table table-bordered" repeat="1">
        <thead>
          <tr>
            <th class="padding-cell">Cantidad</th>
            <th class="padding-cell">Und. Med.</th>
            <th class="padding-cell">Código</th>
            <th class="wide-percent padding-cell">Descripcion</th>
            <th class="wide-percent padding-cell">Marca</th>
            <th class="padding-cell">Precio Unit. Inc. IGV S./</th>
            <th class="padding-cell">Precio Total Inc. IGV S./</th>
          </tr>
        </thead>
        <tbody class="detalles">
          {% for detalle in cotizacion.cotizaciondetalle_set.all %}
          <tr>
            <td class="text-right padding-cell">{{ detalle.cantidad }}</td>
            <td class="padding-cell">{{ detalle.producto.unidad_medida }}</td>
            <td class="padding-cell">{{ detalle.producto.codigo }}</td>
            <td class="padding-cell">{{ detalle.producto }}</td>
            <td class="padding-cell">{{ detalle.producto.marca }}</td>
            <td class="text-right padding-cell">{{ detalle.precio_unitario }}</td>
            <td class="text-right padding-cell">{{ detalle.cantidad|mul:detalle.precio_unitario|floatformat:2 }}</td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="7" class="padding-cell"><small>{{cotizacion.glosa}}</small></td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="6" class="text-right padding-cell"><strong>Total:</strong></td>
            <td colspan="1" class="text-right padding-cell">
              {{ cotizacion.total_cotizacion|floatformat:2 }}
            </td>
          </tr>
        </tfoot>
      </table>
    </div>

    <div class="footer">
      <ul>
        <li>Postor: HAMPI KALLPA E.I.R.L.</li>
        <li>RUC: 20564106861</li>
        <li>Dirección: Clorida Matto de Turner 303 Cusco</li>
        <li>Teléfono: 084-221985 - Fax; 084-221985</li>
        <li>Plazo de Entrega: {{cotizacion.plazo}} días de recibida la orden de compra.</li>
        <li>Validez de la oferta: {{cotizacion.validez}} días</li>
      </ul>

      <p>Las O/C serán recibidas vía fax (084-221985) <u>Asimismo deberán confirmar la recepción</u> al teléfono 084-221985 y al mail: hampikallpa@gmail.com</p>

      <p>Aténtamente,</p>
    </div>
  </body>
</html>

front/templates/front/pdf/entrada.html
{% load mathfilters %}
<!doctype html>
<html>
  <head>
    {% include 'front/pdf/styles.html' %}
  </head>
  <body>
    {% include 'front/pdf/meta.html' %}
    <div class="main-title">
      <h2 class="line-up-down line-grey simple-shadow padding">Detalles de la Entrada</h2>
    </div>

    <div class="info">
      <p>
        <strong>Fecha:</strong> {{ entrada.fecha }} 
      </p>
      <p>
        <strong>Almacén:</strong> {{ entrada.almacen }}
      </p>
      <p>
        <strong>Número de factura:</strong> {{ entrada.numero_factura }}
        <strong>Fecha de factura:</strong> {{ entrada.fecha_factura }}
      </p>
      <p>
        <strong>Número de guía:</strong> {{ entrada.numero_guia }}
        <strong>Fecha de guía:</strong> {{ entrada.fecha_guia }}
      </p>
      {% if entrada.documento != 'G' %}
      <p>
        <strong>Proveedor:</strong> {{ entrada.proveedor.razon_social }}
      </p>
      {% endif %}
      <p>
        <strong>Fecha de Entrada:</strong> {{ entrada.fecha_entrada }}
        <strong>Hora de Entrada:</strong> {{ entrada.hora_entrada }}
      </p>
      <p>
        <strong>Quién:</strong> {{ entrada.quien }}
      </p>
      <p class="line-down">
        <strong>Notas:</strong> {{ entrada.notas }}
      </p>
    </div>

    <div class="details">
      <table class="table table-bordered" repeat="1">
        <thead>
          <tr>
            <th class="padding-cell">Codigo</th>
            <th class="wide-percent padding-cell">Producto</th>
            <th class="padding-cell">Lote Nro</th>
            <th class="padding-cell">Vencimiento</th>
            <th class="padding-cell">Cantidad</th>
            <th class="padding-cell">Unitario</th>
            <th class="padding-cell">Total</th>
          </tr>
        </thead>
        <tbody class="detalles">
          {% for detalle in entrada.entradadetalle_set.all %}
          <tr>
            <td class="padding-cell">{{ detalle.lote.producto.codigo }}</td>
            <td class="padding-cell">{{ detalle.lote.producto }}</td>
            <td class="padding-cell">{{ detalle.lote.numero }}</td>
            <td class="padding-cell">{{ detalle.lote.vencimiento }}</td>
            <td class="text-right padding-cell">{{ detalle.cantidad }}</td>
            <td class="text-right padding-cell">{{ detalle.lote.precio_costo|floatformat:6 }}</td>
            <td class="text-right padding-cell">{{ detalle.cantidad|mul:detalle.lote.precio_costo|floatformat:6 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
</html>

front/templates/front/pdf/factura.html
{% load mathfilters %}
<!doctype html>
<html>
  <head>
    {% include 'front/pdf/styles.html' %}
  </head>
  <body>
    {% include 'front/pdf/meta.html' %}
    <div class="main-title">
      <h2 class="line-up-down line-grey simple-shadow padding">Detalles de la Venta</h2>
    </div>

    <div class="info">
      <p>
        <strong>FECHA:</strong> {{ venta.fecha }} 
      </p>
      <p>
        <strong>ORDEN DE COMPRA:</strong> {{ venta.orden_compra }} 
      </p>
      <p>
        <strong>Número de documento:</strong> {{ venta.numero_documento }}
        <strong>Fecha del documento:</strong> {{ venta.fecha_documento }}
        <strong>Número de guía:</strong> {{ venta.numero_guia }}
      </p>
      <p class="line-down">
        <strong>Cliente:</strong> {{ venta.cliente }} ({{ venta.cliente.numero_documento }})
      </p>
    </div>

    <div class="details">
      <table class="table table-bordered" repeat="1">
        <thead>
          <tr>
            <th class="padding-cell">Código</th>
            <th class="wide-percent padding-cell">Producto</th>
            <th class="padding-cell">Cantidad</th>
            <th class="padding-cell">Unitario</th>
            <th class="padding-cell">Total</th>
          </tr>
        </thead>
        <tbody class="detalles">
          {% for detalle in venta.ventadetalle_set.all %}
          <tr>
            <td class="padding-cell">{{ detalle.lote.producto.codigo }}</td>
            <td class="padding-cell">{{ detalle.lote.producto }} Lote: {{ detalle.lote.numero }}, Vencimiento: {{ detalle.lote.vencimiento }}</td>
            <td class="text-right padding-cell">{{ detalle.cantidad }}</td>
            <td class="text-right padding-cell">{{ detalle.precio_unitario }}</td>
            <td class="text-right padding-cell">{{ detalle.total }}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="4" class="text-right padding-cell"><strong>Sub Total S/.</strong></td>
            <td colspan="1" class="text-right padding-cell">
              {{ subtotal|floatformat:2 }}
            </td>
          </tr>
          <tr>
            <td colspan="4" class="text-right padding-cell"><strong>I.G.V. 18% S/.</strong></td>
            <td colspan="1" class="text-right padding-cell">
              {{ impuesto|floatformat:2 }}
            </td>
          </tr>
          <tr>
            <td colspan="4" class="text-right padding-cell"><strong>Venta Total S/.</strong></td>
            <td colspan="1" class="text-right padding-cell">
              {{ venta.total_venta|floatformat:2 }}
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </body>
</html>

front/templates/front/pdf/guia.html
{% load mathfilters %}
<html>
<head>
<style type="text/css">
  @page {
    size: a4 portrait;

    @frame cliente {             /* Content frame 1 */
        left: 44pt; width: 245pt; top: 90pt; height: 632pt;
    }
    @frame guia {             /* Content frame 2 */
        left: 323pt; width: 245pt; top: 90pt; height: 632pt;
    }
  }
</style>
</head>
<body>
  <div id="cliente">
    {{venta.cliente}}
    {{venta.cliente.numero_documento}}
    {{venta.cliente.direccion}} - {{venta.cliente.ciudad}} - {{venta.cliente.distrito}}
  </div>

  <div id="guia">
    {{venta.fecha_emision|date:"d/m/Y"}}
    {{venta.numero_guia}}
  </div>

  <div id="codcliente">
    {{venta.cliente.codcliente}}
  </div>

  <div id="oc">
    {{venta.orden_compra}}
  </div>

  <div id="condiciones">
    {{venta.condiciones}}
  </div>

  <div id="vencimiento">
    {{venta.vencimiento|date:"d/m/y"}}
  </div>

  <div id="condiciones">
    {{venta.quien}}
  </div>

  <div id="condiciones">
    {{venta.hora}}
  </div>

  <div id="detalles">
    {% for detalle in venta.ventadetalle_set.all %}
      {{detalle.codigo}}
      {{detalle.cantidad}}
      {{detalle.lote.producto}}
      {{detalle.lote.numero}}
      {{detalle.lote.vencimiento|date:"d/m/y"}}
      {{detalle.precio_unidad}}
      {{detalle.total}}
    {% endfor %}
  </div>
  
</body>
</html>

front/templates/front/pdf/inventario.html
{% load mathfilters %}
<!doctype html>
<html>
  <head>
    {% include 'front/pdf/styles.html' %}
  </head>
  <body>
    {% include 'front/pdf/meta.html' %}
    <div class="main-title">
      <h2 class="line-up-down line-grey simple-shadow padding">Inventario de Almacen: {{ almacen }}</h2>
    </div>

    <div class="info">
      <p class="line-down">
        <strong>Impreso el:</strong> {% now "j \d\e F \d\e\l Y - H:i a" %}
      </p>
    </div>

    <div class="details">
      <table class="table table-bordered" repeat="1">
        <thead>
          <tr>
            <th class="padding-cell">Código</th>
            <th class="wide-percent padding-cell">Producto</th>
            <th class="padding-cell">Lote Nro</th>
            <th class="padding-cell">Vencimiento</th>
            <th class="padding-cell">Cantidad</th>
            <th class="padding-cell">Unitario</th>
            <th class="padding-cell">Total</th>
          </tr>
        </thead>
        <tbody class="detalles">
          {% for detalle in stock %}
          <tr>
            <td class="padding-cell">{{ detalle.lote.producto.codigo }}</td>
            <td class="padding-cell">{{ detalle.lote.producto }}</td>
            <td class="padding-cell">{{ detalle.lote.numero }}</td>
            <td class="padding-cell">{{ detalle.lote.vencimiento }}</td>
            <td class="text-right padding-cell">{{ detalle.unidades }}</td>
            <td class="text-right padding-cell">{{ detalle.lote.producto.precio_unidad|floatformat:2 }}</td>
            <td class="text-right padding-cell">{{ detalle.unidades|mul:detalle.lote.producto.precio_unidad|floatformat:2 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <hr>
    <h3 class="line-up-down line-grey simple-shadow padding text-right">Total Valor Venta: {{ total|floatformat:2 }}</h3>
    <h3 class="line-up-down line-grey simple-shadow padding text-right">Total Valor Real: {{ total_real|floatformat:2 }}</h3>
  </body>
</html>

front/templates/front/pdf/venta.html
{% load mathfilters %}
<!doctype html>
<html>
  <head>
    {% include 'front/pdf/styles.html' %}
  </head>
  <body>
    {% include 'front/pdf/meta.html' %}
    <div class="main-title">
      <h2 class="line-up-down line-grey simple-shadow padding">Detalles de la Venta</h2>
    </div>

    <div class="info">
      <p class="text-right frame">
        <strong>Número:</strong> {{ venta.pk }} 
      </p>
      <p>
        <strong>Almacén:</strong> {{ venta.almacen }} <strong>Tipo de Venta:</strong> {{ venta.get_tipo_venta_display }}
        {% if venta.tipo_venta == 'P' %}
        <strong>Estado:</strong> {{ venta.deuda.get_estado_display }}
        {% endif %}
      </p>
      <p>
        <strong>Orden de Compra:</strong> {{ venta.orden_compra }} 
      </p>
      <p>
        <strong>Factura:</strong> {{ venta.numero_factura }}
        <strong>Fecha de factura:</strong> {{ venta.fecha_factura }}
      </p>
      <p>
        <strong>Guía:</strong> {{ venta.numero_guia }}
        <strong>Fecha de guía:</strong> {{ venta.fecha_guia }}
      </p>
      <p class="line-down">
        <strong>Cliente:</strong> {{ venta.cliente }} ({{ venta.cliente.numero_documento }})
      </p>
    </div>

    <div class="details">
      <table class="table table-bordered" repeat="1">
        <thead>
          <tr>
            <th class="padding-cell">Código</th>
            <th class="wide-percent padding-cell">Producto</th>
            <th>Lote Nro</th>
            <th>Vencimiento</th>
            <th class="padding-cell">Cantidad</th>
            <th class="padding-cell">Unitario</th>
            <th class="padding-cell">Total</th>
          </tr>
        </thead>
        <tbody class="detalles">
          {% for detalle in venta.ventadetalle_set.all %}
          <tr>
            <td>{{ detalle.lote.producto.codigo }}</td>
            <td>{{ detalle.lote.producto }}</td>
            <td>{{ detalle.lote.numero }}</td>
            <td>{{ detalle.lote.vencimiento }}</td>
            <td class="text-right padding-cell">{{ detalle.cantidad }}</td>
            <td class="text-right padding-cell">{{ detalle.precio_unitario }}</td>
            <td class="text-right padding-cell">{{ detalle.cantidad|mul:detalle.precio_unitario|floatformat:2 }}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="6" class="text-right padding-cell"><strong>Venta Total:</strong></td>
            <td colspan="1" class="text-right padding-cell">
              {{ venta.total_venta|floatformat:2 }}
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
    {% if venta.tipo_venta == 'P' %}
    <hr>
    <div class="pay">
      <div class="page-header mini">
        <h5 class="line-up-down line-grey simple-shadow padding">Amortizaciones</h5>
      </div>
      <table class="table table-striped table-condensed table-bordered small" repeat="1">
        <thead>
          <tr>
            <th class="padding-cell">Fecha</th>
            <th class="padding-cell">Recibido por</th>
            <th class="padding-cell">Monto</th>
            <th class="padding-cell">Saldo</th>
          </tr>
        </thead>
        <tbody class="detalles">
          {% for amortizacion in amortizaciones %}
          <tr>
            <td class="padding-cell">{{ amortizacion.fecha }}</td>
            <td class="padding-cell">{{ amortizacion.recibido_por.first_name }}</td>
            <td class="text-right padding-cell">{{ amortizacion.monto }}</td>
            <td class="text-right padding-cell">{{ amortizacion.saldo }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}
  </body>
</html>